version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: jordan
      POSTGRES_PASSWORD: jordan
      POSTGRES_DB: Tienda_AIDA
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: always

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile  
    container_name: backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: jordan
      DB_PASSWORD: jordan
      DB_NAME: Tienda_AIDA
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
